import { DeployFunction } from "hardhat-deploy/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import fs from "fs";
import path from "path";

const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  // Optional: keep FHECounter for reference in local dev
  const deployedFHECounter = await deploy("FHECounter", {
    from: deployer,
    log: true,
  });
  console.log(`FHECounter contract: `, deployedFHECounter.address);

  // Deploy JobLinker
  const deployedJobLinker = await deploy("JobLinker", {
    from: deployer,
    log: true,
  });
  console.log(`JobLinker contract: `, deployedJobLinker.address);

  // If on sepolia, copy ABI and address to frontend TS file (no .json in frontend)
  try {
    const networkName = hre.network.name;
    if (networkName === "sepolia") {
      const jobLinkerDeployment = await hre.deployments.get("JobLinker");
      const abi = jobLinkerDeployment.abi;
      const outDir = path.join(process.cwd(), "app", "src", "abi");
      const outFile = path.join(outDir, "JobLinker.ts");
      fs.mkdirSync(outDir, { recursive: true });
      const content = `// Auto-generated by deploy script. Do not edit manually.\n` +
        `export const JOBLINKER_ADDRESS = '${jobLinkerDeployment.address}' as const;\n` +
        `export const JOBLINKER_ABI = ${JSON.stringify(abi, null, 2)} as const;\n`;
      fs.writeFileSync(outFile, content, { encoding: "utf8" });
      console.log(`Wrote ABI and address to ${outFile}`);
    }
  } catch (e) {
    console.warn("Failed to write ABI to frontend:", e);
  }
};
export default func;
func.id = "deploy_all"; // id required to prevent reexecution
func.tags = ["FHECounter", "JobLinker"];
